version: 2

sources:
  - name: natality
    database: "{{ env_var('DBT_DATABASE', 'natality-data-project-dez') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'natality_data') }}"
    tables:
      - name: natality_data  # Must match EXACT table name in BigQuery
        description: "US Natality records"
        columns:
          - name: unique_id
          - name: dob_yy
          - name: dob_date
          - name: dbwt
          - name: mager
          - name: mager9
models:
  - name: stg_avg_m_age_by_year
    description: >
      Calculates average mother age by birth year with statistical measures.
    config:
      materialized: view
    columns:
      - name: year
        description: "Birth year extracted from dob_yy"
      - name: avg_mother_age
        description: "Average mother age rounded to 2 decimal places"
      - name: record_count
        description: "Number of records included in calculation"
      - name: std_dev_age
        description: "Standard deviation of mother ages (2 decimal places)"
      - name: min_age
        description: "Youngest mother age in the year"
      - name: max_age
        description: "Oldest mother age in the year"

  - name: stg_birth_weight_m_age
    description: >
      Calculates birth weight statistics by mother's age group.
      Excludes null values and invalid weights (0 or 9999).
      Uses the mager9 age group classification system.
    config:
      materialized: view
    columns:
    - name: age_group
      description: "Mother's age group code (1-9)"
    - name: age_group_description
      description: "Text description of age group"
    - name: avg_birth_weight
      description: "Average birth weight in grams (2 decimal places)"
    - name: record_count
      description: "Number of records in calculation"
    - name: std_dev_birth_weight
      description: "Standard deviation of weights (2 decimal places)"
    - name: min_birth_weight
      description: "Minimum recorded weight in grams"
    - name: max_birth_weight
      description: "Maximum recorded weight in grams"

  - name: stg_m_age_distr_ealiest
    description: >
      Shows mother's age group distribution for the earliest available year in the dataset.
      Uses mager9 age classification and calculates percentage distribution.
    config:
      materialized: view
    columns:
    - name: age_group
      description: "Mother's age group code (1-9)"
    - name: age_group_description
      description: "Text description of age group category"
    - name: birth_count
      description: "Number of births in this age group"
    - name: percentage
      description: "Percentage of total births (2 decimal places)"
    - name: report_year
      description: "The earliest year analyzed (from dob_yy)"

  - name: stg_m_age_distr_latest
    description: >
      Calculates mother's age group distribution for the most recent year available.
      Uses explicit type casting and validates age groups (1-9).
      Shows both counts and percentage distribution.
    config:
      materialized: view
    columns:
    - name: age_group
      description: "Mother's age category (1-9), explicitly cast as INT64"
    - name: age_group_description
      description: "Human-readable age group label"
    - name: birth_count
      description: "Absolute number of births in this age group"
    - name: percentage
      description: "Percentage of total births (rounded to 2 decimals)"
    - name: report_year
      description: "The latest year analyzed (from dob_yy)"